#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Xuedi\PhpSysMon\Application;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$container = new ContainerBuilder();
$container->setParameter('application_directory', __DIR__);

$loader = new YamlFileLoader($container, new FileLocator());
$loader->load(__DIR__ . '/config/services.yml');

$container->compile();
$container->get(Application::class)->run();


exit(0);

