---
hostname: benny
sensors:
  asus:
    provider: "asuswmisensors-isa-0000"
    items:
      CPU:
        value: "CPU Temperature"
        extra: "CPU Fan"
      Motherboard:
        value: "Motherboard Temperature"
        extra: "Chassis Fan 1"
      Chipset:
        value: "Chipset Temperature"
      VRM:
        value: "CPU VRM Temperature"
      Harddrives:
        value: "Tsensor Temperature"
        extra:
          - "Chassis Fan 2"
          - "Chassis Fan 3"
  corsair:
    provider: "corsairpsu-hid-3-3"
    items:
      Power:
        value: "case temp"
        extra:
          - "psu fan"
          - "power total"
  wifi:
    provider: "iwlwifi_1-virtual-0"
    items:
      WifiCard:
        value: "temp1"
storage:
  root:
    mount: "/"
    partition: "/dev/sdb2"
    fsType: ext4
    disks:
      "/dev/sdb": ssd
  boot:
    mount: "/boot"
    partition: "/dev/sdb1"
    fsType: ext4
    disks:
      "/dev/sdb": ssd
  home:
    mount: "/home/xuedi"
    partition: "/dev/md127"
    fsType: ext4
    disks:
      "/dev/nvme1n1": nvme
      "/dev/nvme2n1": nvme
      "/dev/nvme3n1": nvme
      "/dev/nvme4n1": nvme
  games:
    mount: "/home/xuedi/Games"
    partition: "/dev/sdb3"
    fsType: ext4
    disks:
      "/dev/sdb": ssd
  ubuntu:
    mount: "/run/media/ubuntu"
    partition: "/dev/nvme0n1p1"
    fsType: ext4
    disks:
      "/dev/nvme0n1": nvme
  data:
    mount: "/run/media/Data"
    partition: "/dev/md126"
    fsType: btrfs
    disks:
      "/dev/sda": hdd
      "/dev/sdc": hdd
      "/dev/sdd": hdd
      "/dev/sde": hdd
      "/dev/sdf": hdd
