parameters:
  version: '1.26.0'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $version: '%version%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'command' ]

  Xuedi\PhpSysMon\:
    resource: '../src/*'

  Xuedi\PhpSysMon\Application:
    public: true
    arguments:
      - !tagged_iterator command