name: PHP-Unit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, pcntl, exif, json, pdo, imagick
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: xdebug
        tools: phpunit

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --working-dir=app

    - name: Run tests
      run: |
        make test_unit
